#!/bin/bash
# Based on: http://toroid.org/ams/etc/git-last-modified

AUTO_TAG="[post-commit]"

[ ! -f .commit_in_progress ] && exit

git log -1 --format='%N' HEAD | fgrep -q "$AUTO_TAG" && exit

git diff --name-only HEAD^ HEAD | grep -x '_posts/.*\.md' |\
while read file;
do
  bundle exec fore touch last_modified_at "$file"
  git add "$file"
done

rm .commit_in_progress
git diff-index --quiet --cached HEAD || git commit --no-edit --amend --no-verify && git notes append -m "$AUTO_TAG"
